version: '3.8'
services:
    broker:
        image: confluentinc/cp-kafka:7.3.3
        networks:
          - Kafka_zoo_connectors
        container_name: broker
        restart: always
        user: root
        ports:
          - "9091:9091"
          - "9092:9092"
          - "9093:9093"
          - "29092:29092"

        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT,CLIENTHOST:PLAINTEXT,UI:PLAINTEXT
          KAFKA_LISTENERS: INTERNAL://:9092,CLIENT://:9093,CONTROLLER://broker:29193,CLIENTHOST://0.0.0.0:29092
          KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:9092,CLIENT://localhost:9093,CLIENTHOST://${SERVER_IP}:29092


          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
          KAFKA_JMX_PORT: 9101
          KAFKA_JMX_HOSTNAME: localhost
          KAFKA_PROCESS_ROLES: 'broker,controller'
          KAFKA_NODE_ID: 1
          KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29193'

          KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
          KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
          KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
          KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'

        volumes:
          - ./update_run.sh:/tmp/update_run.sh
          - /path/docker-data/kraft/:/tmp/kraft-combined-logs/
        command: "bash -c 'if [ ! -f /tmp/update_run.sh ]; then echo \"ERROR: Did you forget the update_run.sh file that came with this docker-compose.yml file?\" && exit 1 ; else /tmp/update_run.sh && /etc/confluent/docker/run ; fi'"

    kafka-ui:
      image: provectuslabs/kafka-ui:latest
      container_name: kafka-ui
      restart: always
      networks:
        - Kafka_zoo_connectors
      depends_on:
        - broker
      ports:
        - 8085:8080
      environment:
        - KAFKA_CLUSTERS_0_NAME= Main
        - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS= broker:9092
        - DYNAMIC_CONFIG_ENABLED= true

networks:
  Kafka_zoo_connectors:
    name: Kafka_zoo_connectors
    driver: "bridge"